'\" t
.\" Copyright (c) 2003 Gunnar Ritter
.\"
.\" This software is provided 'as-is', without any express or implied
.\" warranty. In no event will the authors be held liable for any damages
.\" arising from the use of this software.
.\"
.\" Permission is granted to anyone to use this software for any purpose,
.\" including commercial applications, and to alter it and redistribute
.\" it freely, subject to the following restrictions:
.\"
.\" 1. The origin of this software must not be misrepresented; you must not
.\"    claim that you wrote the original software. If you use this software
.\"    in a product, an acknowledgment in the product documentation would be
.\"    appreciated but is not required.
.\"
.\" 2. Altered source versions must be plainly marked as such, and must not be
.\"    misrepresented as being the original software.
.\"
.\" 3. This notice may not be removed or altered from any source distribution.
.\"
.\" Sccsid @(#)paste.1	1.5 (gritter) 4/17/03
.TH PASTE 1 "4/17/03" "Heirloom Toolchest" "User Commands"
.SH NAME
paste \- merge same lines of several files or subsequent lines of one file
.SH SYNOPSIS
\fBpaste\fI file1 file2\fR .\ .\ .
.br
\fBpaste\fB \-d\fIlist\fI file1 file2\fR .\ .\ .
.br
\fBpaste\fB \-s\fR [\fB\-d\fIlist\fR] \fIfile1 file2\fR .\ .\ .
.SH DESCRIPTION
The
.B paste
command,
as shown in the first two synopsis forms,
will combine each set of corresponding lines of the given
.I files
to one single line,
separated by delimiters,
a tabulator (\et) character by default.
If a file contains fewer lines than others,
nothing is printed between the delimiters.
.PP
In the third synopsis form,
.B paste
serially combines all lines of each
.I file
to one single line,
separated by delimiters.
One line per file results.
.PP
If a
.I file
is `\fB\-\fR',
standard input is read.
.PP
The
.B paste
command accepts the following options:
.TP
\fB\-d\fI list\fR
Sets the delimiter characters.
Each single character in
.I list
is used in the given order to separate fields
(former lines of input).
If
.I list
is exhausted,
or a new set of corresponding lines begins,
or (with the \-s option) a new file is printed,
the sequence is repeated starting at the first character.
The following character sequences in
.I list
are special:
.RS +12
.sp
.TS
lfB l.
\en	Newline character.
\et	Tabulator character.
\e\e	Backslash character.
\e0	No delimiter at all.
.TE
.sp
.RE
.TP
.B \-s
Selects the third synopsis form
(serial paste).
.SH "ENVIRONMENT VARIABLES"
.TP
.BR LANG ", " LC_ALL
See
.IR locale (7).
.TP
.B LC_CTYPE
Determines the mapping of bytes to characters
for the argument of the
.B \-d
option.
.SH "SEE ALSO"
cut(1),
locale(7)
