.\"
.\" Sccsid @(#)hostname.1	1.1 (gritter) 10/26/03
.TH HOSTNAME 1 "10/26/03" "Heirloom Toolchest" "User Commands"
.SH NAME
hostname \- set or print name of current host system
.SH SYNOPSIS
\fBhostname\fR [\fIname-of-host\fR]
.SH DESCRIPTION
.I Hostname
prints the node name of the current host.
The super-user can set the node name
by giving an argument.
.SH "SEE ALSO"
uname(1)
