all: config.h logins

logins: logins.o
	$(LD) $(LDFLAGS) logins.o $(LCOMMON) $(LIBS) -o logins

logins.o: logins.c config.h
	$(CC) $(CFLAGS) $(CPPFLAGS) $(XO6FL) $(LARGEF) -c logins.c

install: all
	$(UCBINST) -c logins $(ROOT)$(DEFBIN)/logins
	$(STRIP) $(ROOT)$(DEFBIN)/logins
	$(MANINST) -c -m 644 logins.1 $(ROOT)$(MANDIR)/man1/logins.1

config.h:
	-echo '/*       Auto-generated by make. Do no edit!     */' >config.h
	-echo '#include <shadow.h>' >___build$$$$.c ; \
	echo 'int main(void) { getspent(); return 0; }' >>___build$$$$.c ; \
	$(CC) $(CFLAGS) $(CPPFLAGS) $(LARGEF) $(IWCHAR) -o ___build$$$$ ___build$$$$.c >/dev/null 2>&1 ; \
	if test $$? = 0 && test -f ___build$$$$ ; \
	then    echo '#define SHADOW_PWD' >>config.h ; \
	fi ; \
	rm -f ___build$$$$ ___build$$$$.c

clean:
	rm -f config.h logins logins.o core log *~
