.\"
.\" Sccsid @(#)calendar.1	1.7 (gritter) 10/11/03
.\"
.\" Derived from calendar(1), Unix 32V:
.\"
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"   Redistributions of source code and documentation must retain the
.\"    above copyright notice, this list of conditions and the following
.\"    disclaimer.
.\"   Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"   All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed or owned by Caldera
.\"      International, Inc.
.\"   Neither the name of Caldera International, Inc. nor the names of
.\"    other contributors may be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" USE OF THE SOFTWARE PROVIDED FOR UNDER THIS LICENSE BY CALDERA
.\" INTERNATIONAL, INC. AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL CALDERA INTERNATIONAL, INC. BE
.\" LIABLE FOR ANY DIRECT, INDIRECT INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
.\" EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.TH CALENDAR 1 "10/11/03" "Heirloom Toolchest" "User Commands"
.SH NAME
calendar \- reminder service
.SH SYNOPSIS
\fBcalendar\fR [\fB\-\fR]
.SH DESCRIPTION
.I Calendar 
consults the file `calendar' in the current directory
and prints out lines that contain today's or
tomorrow's date anywhere in the line.
In the C locale,
most reasonable month-day dates such as `Dec. 7,'
`december 7,' `12/7,' etc., are recognized, but not
`7 December' or `7/12'.
On weekends `tomorrow' extends through Monday.
.PP
When 
an argument is present,
.I calendar
does its job for every user
who has a file `calendar' in his login directory
and sends him any positive results by
.IR mail (1).
This can be done daily in the wee hours under control of
.IR cron (1).
.SH "ENVIRONMENT VARIABLES"
.TP 
.BR LANG ,\  LC_ALL
See locale(7).
.TP 
.B LC_CTYPE
Used to separate the first three characters
for abbreviated month names.
.TP 
.B LC_TIME
Determines the abbreviated month names
and the order of month and day.
.SH FILES
calendar
.br
/usr/5lib/calprog to figure out today's and tomorrow's dates
.br
/etc/passwd
.br
/tmp/cal*
.br
egrep, sed, mail subprocesses
.SH "SEE ALSO"
at(1),
cron(1),
mail(1)
.SH NOTES
Your calendar must be public information for you
to get reminder service.
.br
.I Calendar's
extended idea of `tomorrow' doesn't account for
holidays.
