.\"
.\" Sccsid @(#)lex.1	1.5 (gritter) 11/27/05
.\" Derived from lex(1), Unix 7th edition:
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"   Redistributions of source code and documentation must retain the
.\"    above copyright notice, this list of conditions and the following
.\"    disclaimer.
.\"   Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"   All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed or owned by Caldera
.\"      International, Inc.
.\"   Neither the name of Caldera International, Inc. nor the names of
.\"    other contributors may be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" USE OF THE SOFTWARE PROVIDED FOR UNDER THIS LICENSE BY CALDERA
.\" INTERNATIONAL, INC. AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL CALDERA INTERNATIONAL, INC. BE
.\" LIABLE FOR ANY DIRECT, INDIRECT INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
.\" EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH LEX 1 "11/27/05" "Heirloom Development Tools" "User Commands"
.SH NAME
lex \- generator of lexical analysis programs
.SH SYNOPSIS
.HP
.ad l
.nh
\fBlex\fR [\fB\-ctvnVew\fR] [\fB\-Q\fR(\fBy\fR|\fBn\fR)]
[\fB\-Y\ \fIdirectory\fR]
[\fIfiles\fR\ ...]
.br
.ad b
.SH DESCRIPTION
.I Lex
generates programs to be used in simple lexical analyis of text.
The input
.I files
(standard input default)
contain regular expressions
to be searched for, and actions written in C to be executed when
expressions are found.
.PP
A C source program, `lex.yy.c' is generated, to be compiled thus:
.IP
cc lex.yy.c \-ll
.LP
This program, when run, copies unrecognized portions of
the input to the output,
and executes the associated
C action for each regular expression that is recognized.
.PP
The following 
.I lex
program converts upper case to lower,
removes blanks at the end of lines,
and replaces multiple blanks by single blanks.
.IP ""
.nf
.ta \w'[A\-Z] 'u
%%
[A\-Z]	putchar(yytext[0]+\'a\'\-\'A\');
[ ]+$
[ ]+	putchar(\' \');
.fi
.PP
The options have the following meanings.
.TP
.B \-c
Generate output in the `C' language.
This is the default.
.TP
.B \-e
Generates output that can handle multibyte characters,
with \fIyytext[]\fR being of type \fIunsigned char[]\fR.
This option is an extension.
.TP
.B \-n
Opposite of
.BR \-v ;
.B \-n
is default.
.TP
\fB\-Q\fR(\fBy\fR|\fBn\fR)
With
.BR \-Qy ,
a version identification variable is put into lex.yy.c.
With
.B \-Qn
(the default), no such variable is generated.
.TP
.B \-t
Place the result on the standard output instead of in file
`lex.yy.c'.
.TP
.B \-v
Print a one-line summary of statistics of the generated analyzer.
.TP
.B \-V
Causes version information for
.I lex
to be printed.
.TP
.B \-w
Generates output that can handle multibyte characters,
with \fIyytext[]\fR being of type \fIwchar_t[]\fR.
This option is an extension.
.TP
\fB\-Y \fIdirectory\fR
Use `\fIdirectory\fR' to locate driver files,
instead of the default `/usr/ccs/lib/lex'.
This option is an extension.
.SH "SEE ALSO"
yacc(1)
.br
M. E. Lesk and E. Schmidt,
.I LEX \- Lexical Analyzer Generator
