.\"
.\" Sccsid @(#)yes.1	1.2 (gritter) 12/25/06
.TH YES 1XNX "12/25/06" "Heirloom Toolchest" "XENIX System Compatibility"
.SH NAME
yes \- (XENIX) print string repeatedly
.SH SYNOPSIS
\fByes\fR [\fIstring\fR]
.SH DESCRIPTION
The
.I yes
command prints the given string
(or `y' if no string is given)
repeatedly until it is aborted.
