.\"
.\" Sccsid @(#)apropos.1	1.3 (gritter) 1/11/03
.TH APROPOS 1 "1/11/03" "Heirloom Toolchest" "User Commands"
.SH NAME
apropos \- locate commands by keyword lookup
.SH SYNOPSIS
.B apropos
.I keyword \ ...
.SH DESCRIPTION
The
.B apropos
command searches the manual index database
for one-line summaries matching any of the given
.IR keywords .
This is the same as the
.B man
command with the
.B \-k
option.
.SH "SEE ALSO"
man(1)
