.\"
.\" Sccsid @(#)whatis.1	1.3 (gritter) 1/11/03
.TH WHATIS 1 "1/11/03" "Heirloom Toolchest" "User Commands"
.SH NAME
whatis \- display a one-line summary about a keyword
.SH SYNOPSIS
.B whatis
.I command \ ...
.SH DESCRIPTION
The
.B whatis
utility searches the manual index database for one-line summaries
about any of the given
.IR commands .
It is the same as the
.B man
command with the
.B \-f
option.
.SH "SEE ALSO"
man(1)
